# Generated by Django 6.0.5 on 2026-07-04 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Перекус'), ('dinner', 'Ужин')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_time', models.TimeField()),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.PositiveIntegerField(default=0)),
                ('fats', models.PositiveIntegerField(default=0)),
                ('carbs', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'План'), ('eaten', 'Съедено')], default='planned', max_length=20)),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_calories', models.PositiveIntegerField(default=2200)),
                ('target_protein', models.PositiveIntegerField(default=170)),
                ('target_fats', models.PositiveIntegerField(default=70)),
                ('target_carbs', models.PositiveIntegerField(default=230)),
                ('target_water_liters', models.FloatField(default=2.5)),
                ('water_liters', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'День питания',
                'verbose_name_plural': 'Дни питания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('prep_minutes', models.PositiveIntegerField()),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
            options={
                'verbose_name': 'Продукт в приёме пищи',
                'verbose_name_plural': 'Продукты в приёмах пищи',
            },
        ),
    ]
