# Generated by Django 6.0.5 on 2026-07-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Калории, ккал'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.PositiveIntegerField(default=0, verbose_name='Углеводы, г'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionday', verbose_name='День питания'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.PositiveIntegerField(default=0, verbose_name='Жиры, г'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Перекус'), ('dinner', 'Ужин')], max_length=20, verbose_name='Тип приёма'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.PositiveIntegerField(default=0, verbose_name='Белки, г'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='scheduled_time',
            field=models.TimeField(verbose_name='Время по плану'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('planned', 'План'), ('eaten', 'Съедено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal', verbose_name='Приём пищи'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='target_calories',
            field=models.PositiveIntegerField(default=2200, verbose_name='Цель: калории, ккал'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='target_carbs',
            field=models.PositiveIntegerField(default=230, verbose_name='Цель: углеводы, г'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='target_fats',
            field=models.PositiveIntegerField(default=70, verbose_name='Цель: жиры, г'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='target_protein',
            field=models.PositiveIntegerField(default=170, verbose_name='Цель: белки, г'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='target_water_liters',
            field=models.FloatField(default=2.5, verbose_name='Цель: вода, л'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_days', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='water_liters',
            field=models.FloatField(default=0.0, verbose_name='Выпито воды, л'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории, ккал'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.PositiveIntegerField(verbose_name='Углеводы, г'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.PositiveIntegerField(verbose_name='Жиры, г'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list, help_text='Список в кавычках через запятую: ["200 г курицы", "1 ст. л. масла"]', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать в приложении'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_minutes',
            field=models.PositiveIntegerField(verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.PositiveIntegerField(verbose_name='Белки, г'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list, help_text='Список в кавычках через запятую: ["Нарезать курицу", "Обжарить 10 минут"]', verbose_name='Шаги приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
