# Generated by Django 6.0.5 on 2026-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_meal_calories_alter_meal_carbs_alter_meal_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(help_text='Латиницей, без пробелов. Например: chicken-rice. После создания не меняется.', max_length=50, primary_key=True, serialize=False, verbose_name='Код рецепта'),
        ),
    ]
