# Generated by Django 6.0.5 on 2026-07-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_recipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
    ]
