# Generated by Django 6.0.5 on 2026-08-08 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_remove_meal_day_remove_mealitem_meal_delete_recipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('grams', models.FloatField(blank=True, null=True, verbose_name='Порция, г')),
                ('calories', models.FloatField(verbose_name='Калории, ккал')),
                ('protein', models.FloatField(default=0, verbose_name='Белки, г')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры, г')),
                ('carbs', models.FloatField(default=0, verbose_name='Углеводы, г')),
                ('source', models.CharField(choices=[('photo', 'Фото'), ('voice', 'Голос'), ('barcode', 'Штрих-код'), ('manual', 'Вручную')], default='manual', max_length=10, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Дневник питания',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='nutrition_f_user_id_bc7262_idx')],
            },
        ),
    ]
