# Generated by Django 6.0.5 on 2026-07-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('workout', 'Тренировки'), ('nutrition', 'Питание'), ('recovery', 'Восстановление'), ('motivation', 'Мотивация')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('read_time_minutes', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('base', 'База'), ('medium', 'Средний'), ('advanced', 'Продвинутый')], max_length=20)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
