# Generated by Django 6.0.5 on 2026-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('workout', 'Тренировки'), ('nutrition', 'Питание'), ('recovery', 'Восстановление'), ('motivation', 'Мотивация')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='article',
            name='level',
            field=models.CharField(choices=[('base', 'База'), ('medium', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time_minutes',
            field=models.PositiveSmallIntegerField(verbose_name='Время чтения, мин'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
    ]
