# Generated by Django 6.0.5 on 2026-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_article_body_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(help_text='Латиницей, без пробелов. Например: protein-basics. После создания не меняется.', max_length=50, primary_key=True, serialize=False, verbose_name='Код статьи'),
        ),
    ]
