# Generated by Django 6.0.5 on 2026-07-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat_percent', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.IntegerField(blank=True, null=True)),
                ('chest_cm', models.IntegerField(blank=True, null=True)),
                ('hip_cm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Замер тела',
                'verbose_name_plural': 'Замеры тела',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.DateField()),
                ('angle', models.CharField(choices=[('front', 'Спереди'), ('side', 'Сбоку'), ('back', 'Сзади')], default='front', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='progress_photos/')),
            ],
            options={
                'verbose_name': 'Фото прогресса',
                'verbose_name_plural': 'Фото прогресса',
                'ordering': ['-taken_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'История веса',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
