# Generated by Django 6.0.5 on 2026-07-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_fat_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент жира, %'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='chest_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Грудь, см'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='hip_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бёдра, см'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Мышечная масса, кг'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='recorded_at',
            field=models.DateField(verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='waist_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Талия, см'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='angle',
            field=models.CharField(choices=[('front', 'Спереди'), ('side', 'Сбоку'), ('back', 'Сзади')], default='front', max_length=10, verbose_name='Ракурс'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='progress_photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='taken_date',
            field=models.DateField(verbose_name='Дата съёмки'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='recorded_at',
            field=models.DateField(verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='value',
            field=models.FloatField(verbose_name='Вес, кг'),
        ),
    ]
