# Generated by Django 6.0.5 on 2026-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_bodymeasurement_body_fat_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='neck_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шея, см'),
        ),
    ]
