# Generated by Django 6.0.5 on 2026-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_bodymeasurement_neck_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='arm_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рука, см'),
        ),
    ]
