# Generated by Django 6.0.5 on 2026-07-04 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('succeeded', 'Успешно'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=100)),
                ('confirmation_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=20)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('next_charge_date', models.DateField(blank=True, null=True)),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
