# Generated by Django 6.0.5 on 2026-07-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='RUB', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(max_length=20, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('succeeded', 'Успешно'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID платежа в ЮKassa'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_charge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Следующее списание'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('monthly', 'Месячный'), ('annual', 'Годовой')], default='free', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID платежа в ЮKassa'),
        ),
    ]
