# Generated by Django 6.0.5 on 2026-07-04 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('muscle', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('intense', 'Интенсивно'), ('power', 'Сила'), ('cardio', 'Кардио'), ('tone', 'Тонус'), ('pulse', 'Пульс')], max_length=20)),
                ('mode', models.CharField(choices=[('gym', 'Зал'), ('home', 'Дома')], max_length=10)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Программа тренировок',
                'verbose_name_plural': 'Программы тренировок',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight', models.CharField(blank=True, default='—', max_length=50)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercisetemplate')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutprogram')),
            ],
            options={
                'verbose_name': 'Упражнение в программе',
                'verbose_name_plural': 'Упражнения в программах',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('abandoned', 'Брошена')], default='in_progress', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutprogram')),
            ],
            options={
                'verbose_name': 'Сессия тренировки',
                'verbose_name_plural': 'Сессии тренировок',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('was_swapped', models.BooleanField(default=False)),
                ('was_skipped', models.BooleanField(default=False)),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight', models.CharField(blank=True, default='—', max_length=50)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.exercisetemplate')),
                ('original_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name': 'Лог упражнения',
                'verbose_name_plural': 'Логи упражнений',
            },
        ),
    ]
