# Generated by Django 6.0.5 on 2026-07-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='original_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutexercise', verbose_name='Исходное упражнение'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='reps',
            field=models.PositiveSmallIntegerField(verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutsession', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='sets',
            field=models.PositiveSmallIntegerField(verbose_name='Подходы'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.exercisetemplate', verbose_name='Упражнение'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='was_skipped',
            field=models.BooleanField(default=False, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='was_swapped',
            field=models.BooleanField(default=False, verbose_name='Заменено'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='weight',
            field=models.CharField(blank=True, default='—', max_length=50, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='muscle',
            field=models.CharField(max_length=100, verbose_name='Группа мышц'),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код (латиницей)'),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveSmallIntegerField(verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest_seconds',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Отдых, сек'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveSmallIntegerField(verbose_name='Подходы'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercisetemplate', verbose_name='Упражнение'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='weight',
            field=models.CharField(blank=True, default='—', max_length=50, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutprogram', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории, ккал'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Длительность, мин'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код программы'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='intensity',
            field=models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('intense', 'Интенсивно'), ('power', 'Сила'), ('cardio', 'Кардио'), ('tone', 'Тонус'), ('pulse', 'Пульс')], max_length=20, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать в каталоге'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='mode',
            field=models.CharField(choices=[('gym', 'Зал'), ('home', 'Дома')], max_length=10, verbose_name='Где заниматься'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='tone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Акцент'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='elapsed_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность, сек'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('abandoned', 'Брошена')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutprogram', verbose_name='Программа'),
        ),
    ]
