# Generated by Django 6.0.5 on 2026-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_exerciselog_original_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetemplate',
            name='slug',
            field=models.SlugField(help_text='Латиницей, без пробелов. Например: squat-barbell', unique=True, verbose_name='Код (латиницей)'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='id',
            field=models.CharField(help_text='Латиницей, без пробелов. Например: gym-fullbody. После создания не меняется.', max_length=50, primary_key=True, serialize=False, verbose_name='Код программы'),
        ),
    ]
