# Generated by Django 6.0.5 on 2026-07-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercisetemplate_slug_alter_workoutprogram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetemplate',
            name='kinescope_id',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при загрузке видео. Можно вписать ID готового ролика вручную.', max_length=64, verbose_name='Kinescope ID'),
        ),
    ]
