# Generated by Django 6.0.5 on 2026-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_injuries_user_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_newsletter',
            field=models.BooleanField(default=False, verbose_name='Email-рассылка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя из Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('cut', 'Сушка'), ('bulk', 'Набор массы'), ('maintain', 'Поддержание'), ('endurance', 'Выносливость'), ('recomp', 'Рекомпозиция')], max_length=20, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост, см'),
        ),
        migrations.AlterField(
            model_name='user',
            name='injuries',
            field=models.JSONField(blank=True, default=list, verbose_name='Травмы и ограничения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ в админку'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия из Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Новичок'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, verbose_name='Уровень подготовки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Анкета пройдена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, choices=[('gym', 'В зале'), ('home', 'Дома')], max_length=10, verbose_name='Место тренировок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push-уведомления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recommended_program',
            field=models.CharField(blank=True, max_length=50, verbose_name='Рекомендованная программа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='training_days',
            field=models.JSONField(default=list, verbose_name='Дни тренировок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Логин в Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workout_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего тренировок'),
        ),
    ]
