# Generated by Django 6.0.5 on 2026-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_url_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('cut', '   Сушка'), ('bulk', 'Набор массы'), ('maintain', 'Поддержание'), ('endurance', 'Выносливость'), ('recomp', 'Рекомпозиция')], max_length=20, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
