# Generated by Django 6.0.5 on 2026-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('metric', 'Метрическая (кг · см)'), ('imperial', 'Имперская (lb · in)')], default='metric', max_length=10, verbose_name='Система измерения'),
        ),
    ]
